##############################
# Database and Lucene Config #
##############################

spring :
    datasource:
        url: jdbc:h2:tcp://localhost:9999/~/Library/H2Database/beinsport
        username: sa
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: false
        hibernate :
            ddl-auto: update
        properties :
            hibernate.search.default:
                        indexmanager: near-real-time
                        directory_provider: ram
                        indexBase: /tmp/lucene

##############################
#    Application Specific    #
##############################

podcastserver:
    rootfolder: /Users/kevin/Tomcat/podcast/
    #concurrent-download: 2
    #max-update-parallels: 3
    #cover-default-name: cover
    number-of-day-to-download: 1
    #number-of-try: 10
    #server-url: http://192.168.1.203:8080
    #file-container: ${podcastserver.server-url}/podcast
    #download-extention: .psdownload
    #rss-default-number-item: 50
    updateandDownload:
        refresh:
            cron: 0 0 0 * * ?
    externaltools:
        #rtmpdump: /usr/local/bin/rtmpdump
        #ffmpeg: /usr/bin/ffmpeg


##############################
#          Actuator          #
##############################

management:
    context-path: /system

endpoints:
    health:
        sensitive : false

logging:
    path: /private/tmp/logs/podcastserver.log

##############################
#           Server           #
##############################

server:
    port : 8180